<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>login</title>
    <style>

            body {
              background: #999;
              padding: 40px;
              font-family: "Open Sans Condensed", sans-serif;
            }
            
            #bg {
              position: fixed;
              left: 0;
              top: 0;
              width: 100%;
              height: 100%;
              background: url(C:/wamp64/www/client/im.jpg) no-repeat center center fixed;
              background-size: cover;
              -webkit-filter: blur(5px);    
            }
            
            form {
              position: relative;
              width: 250px;
              margin: 0 auto;
              background: rgba(130,130,130,.3);
              padding: 20px 22px;
              border: 1px solid;
              border-top-color: rgba(255,255,255,.4);
              border-left-color: rgba(255,255,255,.4);
              border-bottom-color: rgba(60,60,60,.4);
              border-right-color: rgba(60,60,60,.4);
            }
            
            form input, form button {
              width: 212px;
              border: 1px solid;
              border-bottom-color: rgba(255,255,255,.5);
              border-right-color: rgba(60,60,60,.35);
              border-top-color: rgba(60,60,60,.35);
              border-left-color: rgba(80,80,80,.45);
              background-color: rgba(0,0,0,.2);
              background-repeat: no-repeat;
              padding: 8px 24px 8px 10px;
              font: bold .875em/1.25em "Open Sans Condensed", sans-serif;
              letter-spacing: .075em;
              color: #fff;
              text-shadow: 0 1px 0 rgba(0,0,0,.1);
              margin-bottom: 19px;
            }
            
            form input:focus { background-color: rgba(0,0,0,.4); }
            
            form input.email {
              background-image: url(im.jpg;);
              background-position: 220px 10px;
            }
            
            form input.pass {
              background-image: url(im.jpg;);
              background-position: 223px 8px
            }
            
            ::-webkit-input-placeholder { color: #ccc; text-transform: uppercase; }
            ::-moz-placeholder { color: #ccc; text-transform: uppercase; }
            :-ms-input-placeholder { color: #ccc; text-transform: uppercase; }
            
            form button[type=submit] {
              width: 248px;
              margin-bottom: 0;
              color: #3f898a;
              letter-spacing: .05em;
              text-shadow: 0 1px 0 #133d3e;
              text-transform: uppercase;
              background: #225556;
              border-top-color: #9fb5b5;
              border-left-color: #608586;
              border-bottom-color: #1b4849;
              border-right-color: #1e4d4e;
              cursor: pointer;
            }</style>
</head>
<body>
    

<div id="bg"></div>
<?php if (isset($auth_error)): ?>
                    <div class="alert alert-danger alert-dismissible fade show">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        <?= $auth_error ?>
                    </div>
                <?php endif ?>
                <form action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]); ?>" method="post">

    
  <label for=""></label>
  <input type="text" name="" id="" placeholder="email" class="email" value=""><?= $_POST['email'] ?? '' ?>" maxlength="50" required="">
  <span class="text-danger"><?php if (isset($email_error)) echo $email_error; ?></span>
  <label for=""></label>
  <input type="password" name="" id="" placeholder="password" class="pass">
  <span class="text-danger"><?php if (isset($password_error)) echo $password_error; ?></span>
    
  <button type="submit">login to your account<a href="C:/wamp64/www/projet/index.php"> </button>
  <h2>You don't have account?<a href="registre.php" class="mt-3">Click Here</a>
    
</form>