<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

    <title>Document</title>
</head>
<body>
<?php if (isset($auth_error)): ?>
                    <div class="alert alert-danger alert-dismissible fade show">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        <?= $auth_error ?>
                    </div>
                <?php endif ?>
        
        <div class="form">
          <div id="sendmessage">Inscription!</div>
          <div id="errormessage"></div>
          <form action="create.php"  method="post" role="form" class="contactForm">
            <div class="form-row">
              <div class="form-group col-md-6">
                <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" data-rule="minlen:4" data-msg="Please enter at least 4 chars" />
                <div class="validation"></div>
              </div>
              <div class="form-group col-md-6">
                <input type="texte" class="form-control" name="cid" id="cid" placeholder="Your identity card" data-rule="minlen:8" data-msg="Please enter a valid CID" />
                <div class="validation"></div>
                <span class="text-danger"><?php if (isset($cid_error)) echo $cid_error; ?></span>
              </div>
              <div class="form-group col-md-6">
                <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" data-rule="email" data-msg="Please enter a valid email" />
                <div class="validation"></div>
                <span class="text-danger"><?php if (isset($email_error)) echo $email_error; ?></span>
              </div>
              <div class="form-group col-md-6">
                <input type="text" class="form-control" name="phone" id="phone" placeholder="Your phone number" data-rule="minlen:8" data-msg="Please enter a valid number" />
                <div class="validation"></div>
              </div>
              <div class="form-group col-md-6">
                <input type="text" class="form-control" name="adresse" id="adresse" placeholder="Your adresse" data-msg="Please enter an adresse" />
                <div class="validation"></div>
               </div>
            </div>
            <div class="form-group">
                        <label>Password</label>
                        <input type="password" name="pwd" class="form-control" >
                        <span class="text-danger"><?php if (isset($pwd_error)) echo $password_error; ?></span>
                    </div>  
            <div class="text-center"><button type="submit">S'inscrire</button></div>
          </form>
        </div>
        
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

<!-- Popper JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

</body>
</html>